/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administración_paquetes.capaPresentacion.main.logica;
import Administracion_paquetes.capaLogica.estructuras.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
        grupoEnt.add(jRadioButtonColaEnt);
        grupoEnt.add(jRadioButtonHeapEnt);
        grupoSeg.add(jRadioButtonColaSeg);
        grupoSeg.add(jRadioButtonColaEnt);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEnt = new javax.swing.ButtonGroup();
        grupoSeg = new javax.swing.ButtonGroup();
        jLabeltitulo = new javax.swing.JLabel();
        jLabelCantEnt = new javax.swing.JLabel();
        jTextCantEnt = new javax.swing.JTextField();
        jLabelManEnt = new javax.swing.JLabel();
        jRadioButtonColaEnt = new javax.swing.JRadioButton();
        jRadioButtonHeapEnt = new javax.swing.JRadioButton();
        jLabelCantSeg = new javax.swing.JLabel();
        jTextFieldCantSeg = new javax.swing.JTextField();
        jRadioButtonColaSeg = new javax.swing.JRadioButton();
        jRadioButtonHeapSeg = new javax.swing.JRadioButton();
        jLabelManSeg = new javax.swing.JLabel();
        jLabelTiempoMin = new javax.swing.JLabel();
        jTextFieldTiempoMin = new javax.swing.JTextField();
        jLabelTiempoMax = new javax.swing.JLabel();
        jTextFieldTiempoMax = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabeltitulo.setText("Configuración");

        jLabelCantEnt.setText("Cantidad de ventanillas de entrega:");

        jLabelManEnt.setText("Manejo de Entregas:");

        jRadioButtonColaEnt.setText("Cola de prioridad");

        jRadioButtonHeapEnt.setText("Heap");

        jLabelCantSeg.setText("Cantidad de ventanillas de seguridad:");

        jRadioButtonColaSeg.setText("Cola de prioridad");

        jRadioButtonHeapSeg.setText("Heap");

        jLabelManSeg.setText("Manejo de seguridad:");

        jLabelTiempoMin.setText("Tiempo mínimo de espera:");

        jLabelTiempoMax.setText("Tiempo máximo de espera:");

        jButtonIniciar.setText("Iniciar sistema");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCantEnt)
                                    .addComponent(jLabelManEnt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonColaEnt)
                                        .addGap(41, 41, 41)
                                        .addComponent(jRadioButtonHeapEnt))
                                    .addComponent(jTextCantEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCantSeg)
                                    .addComponent(jLabelManSeg))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonColaSeg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonHeapSeg))
                                    .addComponent(jTextFieldCantSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelTiempoMin)
                                        .addGap(26, 26, 26)
                                        .addComponent(jTextFieldTiempoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelTiempoMax)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonIniciar)
                                            .addComponent(jTextFieldTiempoMax))))
                                .addGap(25, 25, 25)
                                .addComponent(jButtonSalir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabeltitulo)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabeltitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantEnt)
                    .addComponent(jTextCantEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelManEnt)
                    .addComponent(jRadioButtonColaEnt)
                    .addComponent(jRadioButtonHeapEnt))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantSeg)
                    .addComponent(jTextFieldCantSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonColaSeg)
                    .addComponent(jRadioButtonHeapSeg)
                    .addComponent(jLabelManSeg))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTiempoMin)
                    .addComponent(jTextFieldTiempoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTiempoMax)
                    .addComponent(jTextFieldTiempoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciar)
                    .addComponent(jButtonSalir))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        try{                                
            int cantidadEnt=Integer.parseInt(jLabelCantEnt.getText());
            int cantidadSeg=Integer.parseInt(jLabelCantSeg.getText());
            String estructuraEntrega;
            String estructuraSeguridad;
            
            if (jRadioButtonColaEnt.isSelected()==true){
                estructuraEntrega="cola";
            }else if(jRadioButtonHeapEnt.isSelected()==true){
                estructuraEntrega= "heap";
            }else{
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una estructura para la ventanilla de entrega");
                return;
            }
            if(jRadioButtonColaSeg.isSelected()==true){
                estructuraSeguridad= "cola"; 
            }else if(jRadioButtonHeapSeg.isSelected()==true){
                estructuraSeguridad= "heap";
            }else{
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una estructura para la ventanilla de seguridad");
                return;                
            }            
            //Integer.parseInt convierte el texto de las cajas en números enteros               
            new Principal(cantidadEnt, estructuraEntrega, cantidadSeg, estructuraSeguridad,
                    Integer.parseInt(jTextFieldTiempoMin.getText()), Integer.parseInt(jTextFieldTiempoMax.getText())).setVisible(true);
        }
        catch(Exception error){
            System.out.println(error);
        }
        dispose();
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoEnt;
    private javax.swing.ButtonGroup grupoSeg;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelCantEnt;
    private javax.swing.JLabel jLabelCantSeg;
    private javax.swing.JLabel jLabelManEnt;
    private javax.swing.JLabel jLabelManSeg;
    private javax.swing.JLabel jLabelTiempoMax;
    private javax.swing.JLabel jLabelTiempoMin;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JRadioButton jRadioButtonColaEnt;
    private javax.swing.JRadioButton jRadioButtonColaSeg;
    private javax.swing.JRadioButton jRadioButtonHeapEnt;
    private javax.swing.JRadioButton jRadioButtonHeapSeg;
    private javax.swing.JTextField jTextCantEnt;
    private javax.swing.JTextField jTextFieldCantSeg;
    private javax.swing.JTextField jTextFieldTiempoMax;
    private javax.swing.JTextField jTextFieldTiempoMin;
    // End of variables declaration//GEN-END:variables
}
